#!/bin/sh


BLISTS="
    dnsbl-1.uceprotect.net
"

# -- Sanity check on parameters
[ $# -ne 1 ] && ERROR 'Please specify a single IP address'

reverse=$(echo $1 |
  sed -ne "s~^\([0-9]\{1,3\}\)\.\([0-9]\{1,3\}\)\.\([0-9]\{1,3\}\)\.\([0-9]\{1,3\}\)$~\4.\3.\2.\1~p")

if [ "x${reverse}" = "x" ] ; then
      ERROR  "IMHO '$1' doesn't look like a valid IP address"
      exit 1
fi

RDNS=$(dig +short -x $1)

printf "\n"
#printf "Searching for $1 on IP Based Black Lists \n"
for BL in ${BLISTS} ; do
    #printf $(env TZ=UTC date "+%Y-%m-%d_%H:%M:%S_%Z")
    printf "%-40s" " ${reverse}.${BL}."
    IPL="$(dig @8.8.8.8 +short -t a ${reverse}.${BL}.)"
    IPT="$(dig @8.8.4.4 +short -t txt ${reverse}.${BL}.)"
    echo ${IPL:----} ${IPT:----}
done

printf "\n"
